---
- name: Install Active Directory Domain Services
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  notify: Reboot_If_Required

- name: Remove DNS
  win_feature:
    name: DNS
    state: absent
  register: win_feature
  notify: Reboot_If_Required

- name: promote server to be domain controller
  win_domain:
    create_dns_delegation: no
    dns_domain_name: windowsdctest.chrislab.internal
    domain_mode: Win2012R2
    domain_netbios_name: chrislabtest
    forest_mode: Win2012R2
    safe_mode_password: "{{ dsrm_password }}"
    sysvol_path: C:\Windows\SYSVOL
  register: domain_install
  notify: Reboot_If_Required
